---
title: "PSQL connection Test"
format: pdf
---

```{r}
install.packages("RPostgres")
```

Load Libraries

```{r}
library(DBI)
library(dplyr)
library(dbplyr)
setwd("/home/rstudio/r_course_hun/src/db_tutorials")
credentials_filename <- "psql_credential.txt"
```

This needs to be run just one to create the file. After the file is create you need to paste the values

```{r}
if(isFALSE(file.exists(credentials_filename))){
file_lines <- "dbname,
host,
port,
user,
password,"
    
fileConn <- file(credentials_filename)
writeLines(file_lines, fileConn)
close(fileConn)
}

```

This reads the file

```{r}
myData <- readr::read_lines(credentials_filename)
rowNames <- c()
values <- c()
for (i in 1:length(myData)) {
 columna <- strsplit(myData[i], ",")[[1]][1]
 valor <- strsplit(myData[i], ",")[[1]][2]
 rowNames[i] <- columna
 values[i] <- valor
} 
credentials <- data.frame(row.names=rowNames , val=values)
```

This test the connection

```{r}
con <- dbConnect(RPostgres::Postgres(),
                 dbname = credentials['dbname',], 
                 host = credentials['host',],
                 port = as.integer(credentials['port',]),
                 user = credentials['user',],
                 password = credentials['password',])

dbListTables(con)
```

```{r}
dfPerson <- dbGetQuery(con, "SELECT * FROM mimiciii.patients LIMIT 10" )
```

```{r}
patients <- tbl(con, in_schema("mimiciii", "patients"))
```

```{r}
patients %>% head()
```
